{
 "title": "Temperature",
 "description": "Temperature and Humidity levels",
 "tags": [ "temperature" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Current Conditions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_location",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "govee",
     "query": "SELECT (last(\"temperature\") * 1.8) + 32 AS \"temperature\" FROM \"govee\" WHERE (\"location\" !~ /fridge|freezer/) AND $timeFilter GROUP BY time($__interval), \"location\", \"id\" fill(null)",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "porch" }
     ]
    }
   ]
  },
  {
   "title": "Humidity Level",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_location",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "govee",
     "query": "SELECT last(\"humidity\") AS \"humidity\" FROM \"govee\" WHERE (\"location\" !~ /fridge|freezer/) AND $timeFilter GROUP BY time($__interval), \"location\", \"id\" fill(null)",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "porch" }
     ]
    }
   ]
  },
  { "title": "Fridge and Freezer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Fridge Temperature",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_location",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "govee",
     "query": "SELECT (last(\"temperature\") * 1.8) + 32 AS \"temperature\" FROM \"govee\" WHERE (\"location\" = 'fridge') AND $timeFilter GROUP BY time($__interval), \"location\", \"id\" fill(null)",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "porch" }
     ]
    }
   ]
  },
  {
   "title": "Freezer Temperature",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 13, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_location",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "govee",
     "query": "SELECT (last(\"temperature\") * 1.8) + 32 AS \"temperature\" FROM \"govee\" WHERE (\"location\" = 'freezer') AND $timeFilter GROUP BY time($__interval), \"location\", \"id\" fill(null)",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "porch" }
     ]
    }
   ]
  },
  {
   "title": "Fridge Temperature",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "alias": "fridge $tag_sublocation",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tail",
     "query": "SELECT (mean(\"temperature\") * 1.8) + 32 AS \"temperature\" FROM \"govee\" WHERE \"location\" = 'fridge' AND $timeFilter GROUP BY time($__interval), \"sublocation\", \"id\" fill(null)",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "temperature" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "fridge" }
     ]
    },
    {
     "alias": "freezer $tag_sublocation",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tail",
     "query": "SELECT (mean(\"temperature\") * 1.8) + 32 AS \"temperature\" FROM \"govee\" WHERE \"location\" = 'freezer' AND $timeFilter GROUP BY time($__interval), \"sublocation\", \"id\" fill(null)",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "temperature" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "fridge" }
     ]
    }
   ]
  },
  { "title": "Time Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Air Temperature",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "alias": "$tag_location $tag_sublocation",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tail",
     "query": "SELECT (mean(\"temperature\") * 1.8) + 32 AS \"temperature\" FROM \"govee\" WHERE (\"location\" !~ /^(fridge|freezer)/) AND $timeFilter GROUP BY time($__interval), \"location\", \"sublocation\", \"id\" fill(null)",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "temperature" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "fridge" }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "alias": "$tag_location",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "govee",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "humidity" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  { "title": "Battery Levels and Other Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Battery Charge",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_location",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "govee",
     "select": [
      [
       { "params": [ "battery_level" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "battery" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}